---
title: "DataDescription"
format: html
---

## Fields

**freq**: time frequency

- [A]Annual

**indic_ur**: urban audit indicator

- [DE4001V]Population with the place of residence in the same dwelling, in the year before

- [DE4002V]Population with the place of residence in another dwelling in the same city/FUA, in the year before

- [DE4003V]Population with the place of residence in another dwelling outside the current city/FUA in the same country, in the year before

- [DE4004V]Population with the place of residence in another EU country, in the year before

- [DE4005V]Population with the place of residence outside the EU, in the year before

- [DE2001V]Nationals

- [DE2002V]EU foreigners

- [DE2003V]Non-EU foreigners

- [DE2008V]Native-born

- [DE2009V]Foreign-born

- [DE2010V]Foreign-born in a EU country

- [DE2011V]Foreign-born in a non-EU country

- [DE2012V]Foreigners

- [DE2001I]Nationals as a proportion of population

- [DE2007I]Foreigners as a proportion of population

- [DE2008I]Native-born as a proportion of population

- [DE2009I]Foreign-born as a proportion of population

- [DE2002I]EU foreigners as a proportion of population

- [DE2003I]Non-EU foreigners as a proportion of population


**c_birth**: Country of Birth

- [NEU27_2007_FOR]Non-EU27 countries (2007-2013) nor reporting country

- [FOR]Foreign country

- [NAT]Reporting country

**sex**: Gender 

- [T]total

- [M]males

- [F]females

**age**: 

- [Y18-54]From 18 to 54 years

- [Y18-59]From 18 to 59 years

- [Y18-64]From 18 to 64 years

- [Y_GE18]18 years or over

- [Y20-64]From 20 to 64 years

- [Y25-54]From 25 to 54 years

- [Y25-59]From 25 to 59 years

- [Y55-64]From 55 to 64 years

- [Y_GE55]55 years or over

- [Y_GE60]60 years or over

- [Y_GE65]65 years or over

**deg_urb**: degree of urbanization

- [TOTAL]Total

- [DEG1]Cities

- [DEG2]Towns and suburbs

- [DEG3]Rural areas

- [NRP]No response

**indic_il**: income and living condition indicators

- [MEI_E]Mean equivalised net income

- [MED_E]Median equivalised net income

**isced11**: international standard classification of education

- [ED3-8]Upper secondary, post-secondary non-tertiary and tertiary education (levels 3-8)

- [ED3_4]Upper secondary and post-secondary non-tertiary education (levels 3 and 4)

- [ED3_4GEN]Upper secondary and post-secondary non-tertiary education (levels 3 and 4) - general

- [ED3_4VOC]Upper secondary and post-secondary non-tertiary education (levels 3 and 4) - vocational

- [ED5-8]Tertiary education (levels 5-8)

- [ED0-2]Less than primary, primary and lower secondary education (levels 0-2)

- [ED3_4]Upper secondary and post-secondary non-tertiary education (levels 3 and 4)

- [ED5-8]Tertiary education (levels 5-8)

- [NRP]No response, [UNK]Unknown

**agedef**: age definition

- [REACH]Age reached during the year

- [COMPLET]Age in completed years

**tenure**: tenured status

- [OWN]Owner

- [RENT]Tenant

**unit**: unit of measure

- [PC]percentage

- [THS_PER]Thousand persons

- [EUR]Euro

- [NAC]National currency

- [PPS]Purchasing power standard (PPS)

**cities**: we ignore the concrete city fields, instead, we use countries.

- [BE] Belgium

- [BG] Bulgaria

- [CZ] Czech Republic

- [DK] Denmark

- [DE] Germany

- [EE] Estonia

- [IE] Ireland

- [EL] Greece

- [ES] Spain

- [FR] France

- [IT] Italy

- [CY] Cyprus

- [LV] Latvia

- [LT] Lithuania

- [LU] Luxembourg(Grand Duchy)

- [HU] Hungary

- [MT] Malta

- [NL] Netherlands

- [AT] Austria

- [PL] Poland

- [PT] Portugal

- [RO] Romania

- [SI] Slovenia

- [SK] Slovakia

- [FI] Finland

- [SE] Sweden

- [NO] Norge

- [CH] Schweiz/Suisse

- [UK] United Kingdom

**geo**: Geopolitical Entity, the same as countries

## urb_cpopcb

Title: Population by citizenship and country of birth - cities and greater cities.

Link: https://ec.europa.eu/eurostat/databrowser/view/urb_cpopcb/default/table?lang=en&category=mi.mii.mii_urb

Description: Contains population data classified by citizenship and country of birth for urban and metropolitan areas, enabling demographic and migration trend analyses.

Fields: freq, indic_ur, cities

Ranges: 1990-2024


## ilc_di16

Title: Mean and median income by group of country of birth (population aged 18 and over).

Link: https://ec.europa.eu/eurostat/databrowser/view/ilc_di16/default/table?lang=en&category=mi.mii.mii_soinc.mii_ip

Description: Similar to ilc_di15 but focuses on grouping by country of birth, highlighting income disparities among native-born and foreign-born populations.

Fields: freq,unit,indic_il,c_birth,sex,age,geo

Ranges: 2003-2023


## ilc_iw16

Link: https://ec.europa.eu/eurostat/databrowser/view/ilc_iw16/default/table?lang=en&category=mi.mii.mii_soinc.mii_ip

Title: In-work at-risk-of-poverty rate by group of country of birth(population aged 18 and over).

Description: Captures poverty rates among employed individuals, broken down by citizenship groups.

Fields: freq,unit,c_birth,sex,age,geo
  
Ranges: 2003-2023


## ilc_peps06n:

Link: https://ec.europa.eu/eurostat/databrowser/view/ilc_peps06/default/table?lang=en&category=mi.mii.mii_soinc.mii_pe

Title: Persons at risk of poverty or social exclusion by group of country of birth (population aged 18 and over).

Description: Similar to ilc_peps05n but categorized by country of birth.

Fields: freq,c_birth,sex,age,unit,geo

Ranges: 2003-2020


## ilc_lvps16:

Link: https://ec.europa.eu/eurostat/databrowser/view/ilc_lvps16/default/table?lang=en&category=mi.mii.mii_soinc.mii_lc

Title: Distribution of population by group of country of birth and tenure status (population aged 18 and over).

Description: Reports housing tenure types (e.g., owned or rented) across groups defined by country of birth.

Fields: freq,unit,tenure,c_birth,sex,age,geo

Ranges: 2003-2024


## edat_lfs_9912:

Link: https://ec.europa.eu/eurostat/databrowser/view/edat_lfs_9912/default/table?lang=en&category=mi.mii.mii_educ.mii_edata

Title: Population by educational attainment level, sex, age, and country of birth (%).

Description: Shows educational attainment levels across demographic and migration status categories.

Fields: freq,unit,sex,isced11,c_birth,age,geo

Ranges: 2004-2023


## edat_lfs_9915

Link: https://ec.europa.eu/eurostat/databrowser/view/edat_lfs_9915/default/table?lang=en&category=mi.mii.mii_educ.mii_edata

Title: Population by educational attainment level, sex, age, country of birth and degree of urbanisation (%)

Description: Shows educational attainment levels across demographic and migration status categories.

Fields: freq,unit,sex,isced11,c_birth,age,geo,deg_urb

Ranges: 2004-2023


## lfst_r_lfur2gacu

Link: https://ec.europa.eu/eurostat/databrowser/view/lfst_r_lfur2gacu/default/table?lang=en&category=mi.mii.mii_emp_r.mii_une_r

Title: Unemployment rates by sex, age, country of birth and degree of urbanisation

Fields: freq,unit,deg_urb,c_birth,sex,age,geo

Ranges: 1995-2023


## lfst_r_eredcobu

Link: https://ec.europa.eu/eurostat/databrowser/view/lfst_r_eredcobu/default/table?lang=en&category=mi.mii.mii_emp_r.mii_em_r

Title: Employment rates by sex, age, educational attainment level, country of birth and degree of urbanisation

Fields: freq,deg_urb,c_birth,isced11,age,sex,unit,geo

Ranges: 1995-2023


## ilc_di03

Link: https://ec.europa.eu/eurostat/databrowser/view/ilc_di03$defaultview/default/table?lang=en

Title: Mean and median income by age and sex

Fields: freq,unit,indic_il,c_birth,sex,age,geo

Ranges: 1995-2023


## demo_pjangroup

Link: https://ec.europa.eu/eurostat/databrowser/view/demo_pjangroup$defaultview/default/table?lang=en

Title: Population on 1 January by age group and sex

Fields: age,geo,sex,time,freq,unit

Ranges: 1960-2023


## migr_imm8

Link: https://ec.europa.eu/eurostat/databrowser/view/migr_imm8$defaultview/default/table?lang=en

Title: Immigration by age and sex

Fields: age,geo,sex,time,freq,unit

Ranges: 1990-2022












