---
title: "Question1"
author: "Puwen Wen"
format: html
editor: visual
---

## Model Set Up

### Package loading

```{r}
library(plm)
```
### income_NAT model with lags

```{r}

panelA$income_ratio <- (panelA$Mean_income_FOR/panelA$Mean_income_NAT)*100
panelA$Immigration_percentage <- panelA$Imigration_ratio*100


panelA_reg <- panelA |> group_by(geo,c_birth)|>
  mutate(income_NAT_lag1 = dplyr::lag(Mean_income_NAT,n = 1))|>
  mutate(Immigration_percentage_lag1 = dplyr::lag(Immigration_percentage,n = 1))|>
  mutate(income_NAT_lag2 = dplyr::lag(Mean_income_NAT, n = 2))|>
  mutate(Immigration_percentage_lag2 = dplyr::lag(Immigration_percentage,n = 2))|>
  ungroup()|>
  mutate(c_birth_onehot=case_when(c_birth=='NEU_FOR'~1,c_birth=='EU_FOR'~0))



model_with_lags <- plm(Mean_income_NAT ~ Immigration_percentage+Immigration_percentage_lag1+Immigration_percentage_lag2+income_NAT_lag1+income_NAT_lag2,data = panelA_reg, index = c("geo", "TIME_PERIOD"), model = "random")
summary(model_with_lags)
```


### income_ratio model with lags

```{r}

panelA$income_ratio <- (panelA$Mean_income_FOR/panelA$Mean_income_NAT)*100
panelA$Immigration_percentage <- panelA$Imigration_ratio*100


panelA_reg <- panelA |> group_by(geo,c_birth)|>
  mutate(income_ratio_lag1 = dplyr::lag(income_ratio,n = 1))|>
  mutate(Immigration_percentage_lag1 = dplyr::lag(Immigration_percentage,n = 1))|>
  mutate(income_ratio_lag2 = dplyr::lag(income_ratio, n = 2))|>
  mutate(Immigration_percentage_lag2 = dplyr::lag(Immigration_percentage,n = 2))|>
  ungroup()|>
  mutate(c_birth_onehot=case_when(c_birth=='NEU_FOR'~0,c_birth=='EU_FOR'~1))



model_with_lags <- plm(income_ratio ~ Immigration_percentage+Immigration_percentage_lag1+Immigration_percentage_lag2+income_ratio_lag1+income_ratio_lag2,data = panelA_reg, index = c("geo", "TIME_PERIOD"), model = "random")
summary(model_with_lags)
```

### DiD model
We choose the country of birth of immigrants as treatment variable. Since immigrants of refugee crisis mainly come from non-eu countries. EU foreigners are as control group. We choose 2015(2011-2017 are possible) as the time point that determine the post variable.

```{r}

panelA_DID <- panelA |> group_by(geo,c_birth)|>
  mutate(income_ratio_lag1 = dplyr::lag(income_ratio,n = 1))|>
  mutate(Immigration_percentage_lag1 = dplyr::lag(Immigration_percentage,n = 1))|>
  mutate(income_ratio_lag2 = dplyr::lag(income_ratio, n = 2))|>
  mutate(Immigration_percentage_lag2 = dplyr::lag(Immigration_percentage,n = 2))|>
  ungroup()|>
  mutate(c_birth_onehot=case_when(c_birth=='NEU_FOR'~1,c_birth=='EU_FOR'~0))|>
  mutate(post = case_when(TIME_PERIOD < 2015 ~0,TIME_PERIOD >2014~1))|>
  mutate(post_treatment = post*c_birth_onehot)

model_with_interactions <- plm(
  income_ratio ~ Immigration_percentage +
                 Immigration_percentage_lag1 +
                 Immigration_percentage_lag2 +
                 income_ratio_lag1 +
                 income_ratio_lag2 + 
                 c_birth_onehot + 
                 post +
                 post_treatment,
  data = panelA_DID,
  index = c("geo", "TIME_PERIOD"),
  model = "random"
)

summary(model_with_interactions)

```
